### ISSUE TITLE
authinjection.sh is missing

### ISSUE THREAD

**Issue by 5l1v3r1** [haroonawanofficial/Authentication_Injection#1]
can you please add it?

**Comment by vactum0** [comment]
same

![image](https://user-images.githubusercontent.com/29106305/73119314-e3004c00-3f81-11ea-9429-540057fa6f2a.png)

**Comment by haroonawanofficial** [comment]
I update it in few minutes

**Comment by haroonawanofficial** [comment]
try and confirm, it will work
